name: 'Deduplicate SARIF'
description: 'Deduplicate SARIF files'
author: 'Matthew Chadder'
inputs:
  sarif-file:
    description: 'Path to the SARIF file to deduplicate'
    required: true
runs:
  using: 'docker'
  image:
    name: 'mchadd3rpan/jq:latest'
